quarkus:
  image:
    ## Name of the image you want to build/deploy
    ## Defaults to the release name
    name: quay.io/ablock/gitops-helm-quarkus
  deploy:
    ## Number of pod replicas to deploy
    replicas: 1
